package easyDifficultyset;

import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;

import java.util.Scanner;
import java.util.Set;

public class _389_FindTheDifference {

	/*	Given two strings s and t which consist of only lowercase letters.

	String t is generated by random shuffling string s and then add one more 
	letter at a random position.

	Find the letter that was added in t.

	Example:

	Input:
	s = "abcd"
	t = "abcde"

	Output:
	e

	Explanation:
	'e' is the letter that was added.
	*/
	
	public static void main(String[] args) {
		Scanner sc=new Scanner(System.in);
		Boolean flag=true;
		String s,t;
		while(flag){
			System.out.println("Enter the string s : ");
			s=sc.nextLine();
			System.out.println("Enter the string t : ");
			t=sc.nextLine();
			System.out.println("The letter that was added to t is:   "+findTheDifference(s, t));
			System.out.println("Want to continue: yes:1 no:0 :");
			if(Integer.parseInt((sc.nextLine()))!=1) flag=false;
		}
		sc.close();
	}
	public static char findTheDifference(String s, String t) {
		char diffch=' ';
		HashMap<Character, Integer> Hstrs=new HashMap<Character,Integer>();
		
		for (int i = 0; i < s.length(); i++) {
			if(Hstrs.containsKey(s.charAt(i))){
				int val=Hstrs.get(s.charAt(i));
				Hstrs.replace(s.charAt(i), val+1);
			}else{
				Hstrs.put(s.charAt(i), 1);
			}
		}
		
		for (int i = 0; i < t.length(); i++) {
			if(Hstrs.containsKey(t.charAt(i))){
				int val=Hstrs.get(t.charAt(i));
				Hstrs.replace(t.charAt(i), val+1);
			}else{
				Hstrs.put(t.charAt(i), 1);
			}
		}
		
		Set set = Hstrs.entrySet();
	      Iterator iterator = set.iterator();
	      while(iterator.hasNext()) {
	         Map.Entry mentry = (Map.Entry)iterator.next();
	         if(((Integer)mentry.getValue()%2)==1) diffch=(Character)mentry.getKey(); 
	      } 
		return diffch;
    }

}
